### ISSUE TITLE
What parameter did you use?

### ISSUE THREAD

**Issue by ozbillwang** [ka7/misspell_fixer#19]
Regarding the PR (https://github.com/ansible/ansible/pull/23644), I am curious what parameters you used to get the result.

I tried all options such as -u, -g, -R, -V, -D, but only get one change, still can't get the same result.

    misspell_fixer.sh -ugRVD contrib/inventory/ec2.py

```
-optional region environement variable if region is 'auto'
+optional region environment variable if region is 'auto'

```
If compare with https://github.com/ansible/ansible/pull/23644/files#diff-c2e371537339bbab5d9d0cc5d6cb7adc, there are three changes.

**Comment by ka7** [comment]
yea.. usually I run the script, check the results manually (sometimes it just changes stupid things, like changing variables, ... )
..and sometimes, I see an error at the exact same spot jumping into my eyes - so I might manual edit it.

usually I run it like
./misspell_fixer.sh -s -v -D ../someProject/ > ../someProject/spelling.txt
then going over the spelling.txt, copy out the filenames which seems to be ok, then run
./misspell_fixer.sh -s -v -D -r -n ../someProject/path/to/file.c 

( first do a clone on github, set upstream locally to that,  branch to spellling_fixes )
There is lot of room for improvement and more automatism.. working on that.
